function out = at_least_version(fixed_version, var_version)
%   Parses version no. strings in the format 'X.X.X' (up to 100 digits) and
%   compare
ver_array = cell2mat(...
    cellfun(...
    @(x) pad_to_sz(cellfun(@(y) str2num(y), strsplit(x, '.')), 100), ...
    {fixed_version,var_version}', ...
    'UniformOutput', 0 ...
    ) ...
    );
out = sum(sign(diff(ver_array)) .* 2.^(size(ver_array, 2):-1:1)) >= 0;
end
function out = pad_to_sz(in, sz)
out = zeros([1, sz]);
out(1:numel(in)) = in;
end